// ============================================================================
// data.js — static content for Mesa Cheia
//
// Nothing in this file depends on game state. It only defines the raw
// content the game draws from: menu items, guest names, UI copy in three
// languages, and the tables used to pick a natural-sounding voice for
// text-to-speech. `app.js` reads these constants but never mutates them.
// ============================================================================

// Full catalogue of dishes/drinks, grouped by course. Each item has a stable
// `id` (used everywhere else to refer to the dish) plus its name in each of
// the three supported languages (pt/en/es). A "menu of the day" is just a
// random (or hand-picked) subset of these arrays — see buildTable() in app.js.
const MENU_POOL = {
  entrada: [
    { id: "e1", pt: "Carpaccio de Lombo de Novilho", en: "Beef Tenderloin Carpaccio", es: "Carpaccio de Solomillo de Ternera" },
    { id: "e2", pt: "Bife Tártaro", en: "Beef Tartare", es: "Tartar de Ternera" },
    { id: "e3", pt: "Presunto Pata Negra", en: "Pata Negra Ham", es: "Jamón Pata Negra" },
    { id: "e4", pt: "Cecina de Wagyu", en: "Wagyu Cecina", es: "Cecina de Wagyu" },
    { id: "e5", pt: "Croquetes de Novilho", en: "Veal Croquettes", es: "Croquetas de Ternera" },
    { id: "e6", pt: "Tutano na Brasa", en: "Grilled Bone Marrow", es: "Tuétano a la Brasa" },
    { id: "e7", pt: "Foie Gras", en: "Foie Gras", es: "Foie Gras" },
    { id: "e8", pt: "Burrata DOP", en: "DOP Burrata", es: "Burrata DOP" },
    { id: "e9", pt: "Pleurotus Grelhados", en: "Grilled Oyster Mushrooms", es: "Setas Pleurotus a la Parrilla" },
    { id: "e10", pt: "Ostras Frescas", en: "Fresh Oysters", es: "Ostras Frescas" },
    { id: "e11", pt: "Ceviche de Corvina", en: "Sea Bass Ceviche", es: "Ceviche de Corvina" },
    { id: "e12", pt: "Vieiras Salteadas", en: "Seared Scallops", es: "Vieiras Salteadas" },
    { id: "e13", pt: "Tártaro de Atum", en: "Tuna Tartare", es: "Tartar de Atún" },
    { id: "e14", pt: "Salmão Fumado", en: "Smoked Salmon", es: "Salmón Ahumado" },
    { id: "e15", pt: "Camarão ao Alho", en: "Garlic Prawns", es: "Gambas al Ajillo" },
    { id: "e16", pt: "Polvo à Brasa", en: "Grilled Octopus", es: "Pulpo a la Brasa" },
    { id: "e17", pt: "Terrine de Pato", en: "Duck Terrine", es: "Terrina de Pato" },
    { id: "e18", pt: "Espargos Verdes Grelhados", en: "Grilled Green Asparagus", es: "Espárragos Verdes a la Parrilla" },
    { id: "e19", pt: "Alcachofras Confitadas", en: "Confit Artichokes", es: "Alcachofas Confitadas" },
    { id: "e20", pt: "Queijo de Cabra Grelhado", en: "Grilled Goat Cheese", es: "Queso de Cabra a la Parrilla" },
  ],
  principal: [
    { id: "p1", pt: "Vazia", en: "Flank Steak", es: "Vacío" },
    { id: "p2", pt: "Entrecôte", en: "Ribeye Steak", es: "Entrecot" },
    { id: "p3", pt: "Lombo", en: "Beef Tenderloin", es: "Solomillo" },
    { id: "p4", pt: "Chateaubriand", en: "Chateaubriand", es: "Chateaubriand" },
    { id: "p5", pt: "Bife Ancho", en: "Ancho Steak", es: "Bife Ancho" },
    { id: "p6", pt: "Lomo Bajo", en: "Lomo Bajo", es: "Lomo Bajo" },
    { id: "p7", pt: "T-Bone", en: "T-Bone Steak", es: "Chuletón T-Bone" },
    { id: "p8", pt: "Chuletón", en: "Chuletón (Bone-in Ribeye)", es: "Chuletón" },
    { id: "p9", pt: "Rib Eye Wagyu do Japão", en: "Japanese Wagyu Rib Eye", es: "Rib Eye Wagyu de Japón" },
    { id: "p10", pt: "Prego de Vazia", en: "Steak Sandwich", es: "Bocadillo de Vacío" },
    { id: "p11", pt: "Hambúrguer com Ovo e Cheddar", en: "Burger with Egg and Cheddar", es: "Hamburguesa con Huevo y Cheddar" },
    { id: "p12", pt: "Couve-Flor Assada na Brasa", en: "Roasted Cauliflower", es: "Coliflor Asada a la Brasa" },
    { id: "p13", pt: "Beetartar de Beterraba", en: "Beetroot Tartare", es: "Tartar de Remolacha" },
    { id: "p14", pt: "Costeleta de Borrego", en: "Lamb Chops", es: "Chuletas de Cordero" },
    { id: "p15", pt: "Bacalhau à Brasa", en: "Grilled Codfish", es: "Bacalao a la Brasa" },
    { id: "p16", pt: "Robalo Grelhado", en: "Grilled Sea Bass", es: "Lubina a la Parrilla" },
    { id: "p17", pt: "Polvo Assado", en: "Roasted Octopus", es: "Pulpo Asado" },
    { id: "p18", pt: "Frango do Campo na Brasa", en: "Grilled Free-Range Chicken", es: "Pollo de Corral a la Brasa" },
    { id: "p19", pt: "Risotto de Cogumelos Selvagens", en: "Wild Mushroom Risotto", es: "Risotto de Setas Silvestres" },
    { id: "p20", pt: "Magret de Pato", en: "Duck Breast", es: "Magret de Pato" },
  ],
  acompanhamento: [
    { id: "a1", pt: "Batatas Fritas", en: "French Fries", es: "Patatas Fritas" },
    { id: "a2", pt: "Batatas Fritas com Trufa", en: "Truffle Fries", es: "Patatas Fritas con Trufa" },
    { id: "a3", pt: "Puré de Batata Trufado", en: "Truffled Mashed Potato", es: "Puré de Patata con Trufa" },
    { id: "a4", pt: "Brás de Cogumelos", en: "Mushroom Brás", es: "Brás de Setas" },
    { id: "a5", pt: "Arroz de Forno com Enchidos", en: "Baked Rice with Smoked Sausage", es: "Arroz al Horno con Embutido" },
    { id: "a6", pt: "Pimentos Piquillo", en: "Piquillo Peppers", es: "Pimientos del Piquillo" },
    { id: "a7", pt: "Bimis Salteados", en: "Sautéed Broccolini", es: "Bimi Salteado" },
    { id: "a8", pt: "Legumes na Brasa", en: "Grilled Vegetables", es: "Verduras a la Brasa" },
    { id: "a9", pt: "Salada Coleslaw", en: "Coleslaw", es: "Ensalada Coleslaw" },
    { id: "a10", pt: "Corações de Alface", en: "Lettuce Hearts", es: "Corazones de Lechuga" },
  ],
  sobremesa: [
    { id: "s1", pt: "Pavlova de Frutos Vermelhos", en: "Red Berry Pavlova", es: "Pavlova de Frutos Rojos" },
    { id: "s2", pt: "Chocolate Beef", en: "\"Chocolate Beef\" Dessert", es: "Chocolate Beef" },
    { id: "s3", pt: "Tarta de Queso", en: "Cheesecake", es: "Tarta de Queso" },
    { id: "s4", pt: "Texturas de Avelã", en: "Hazelnut Textures", es: "Texturas de Avellana" },
    { id: "s5", pt: "Tarte de Limão Merengada", en: "Lemon Meringue Tart", es: "Tarta de Limón Merengada" },
    { id: "s6", pt: "Seleção de Queijos", en: "Cheese Selection", es: "Selección de Quesos" },
    { id: "s7", pt: "Crème Brûlée", en: "Crème Brûlée", es: "Crème Brûlée" },
    { id: "s8", pt: "Mousse de Chocolate 70%", en: "70% Chocolate Mousse", es: "Mousse de Chocolate 70%" },
    { id: "s9", pt: "Tiramisu Clássico", en: "Classic Tiramisu", es: "Tiramisú Clásico" },
    { id: "s10", pt: "Soufflé de Chocolate", en: "Chocolate Soufflé", es: "Suflé de Chocolate" },
    { id: "s11", pt: "Baba ao Rum", en: "Rum Baba", es: "Baba al Ron" },
    { id: "s12", pt: "Tarte Tatin de Maçã", en: "Apple Tarte Tatin", es: "Tarta Tatin de Manzana" },
    { id: "s13", pt: "Panna Cotta de Baunilha", en: "Vanilla Panna Cotta", es: "Panna Cotta de Vainilla" },
    { id: "s14", pt: "Gelado Artesanal", en: "Artisan Ice Cream", es: "Helado Artesanal" },
    { id: "s15", pt: "Fondant de Chocolate", en: "Chocolate Fondant", es: "Fondant de Chocolate" },
    { id: "s16", pt: "Mil-Folhas de Baunilha", en: "Vanilla Mille-Feuille", es: "Milhojas de Vainilla" },
    { id: "s17", pt: "Torta de Amêndoa e Laranja", en: "Almond and Orange Cake", es: "Tarta de Almendra y Naranja" },
    { id: "s18", pt: "Sorbet da Época", en: "Seasonal Fruit Sorbet", es: "Sorbete de Temporada" },
    { id: "s19", pt: "Cheesecake de Frutos Vermelhos", en: "Red Berry Cheesecake", es: "Tarta de Queso con Frutos Rojos" },
    { id: "s20", pt: "Petit Gâteau com Gelado", en: "Petit Gâteau with Ice Cream", es: "Petit Gâteau con Helado" },
  ],
  bebida: [
    { id: "b1", pt: "Água com Gás", en: "Sparkling Water", es: "Agua con Gas" },
    { id: "b2", pt: "Água sem Gás", en: "Still Water", es: "Agua sin Gas" },
    { id: "b3", pt: "Vinho Tinto da Casa", en: "House Red Wine", es: "Vino Tinto de la Casa" },
    { id: "b4", pt: "Vinho Branco da Casa", en: "House White Wine", es: "Vino Blanco de la Casa" },
    { id: "b5", pt: "Refrigerante", en: "Soft Drink", es: "Refresco" },
    { id: "b6", pt: "Cerveja", en: "Beer", es: "Cerveza" },
    { id: "b7", pt: "Sumo de Laranja", en: "Orange Juice", es: "Zumo de Naranja" },
    { id: "b8", pt: "Vinho Rosé da Casa", en: "House Rosé Wine", es: "Vino Rosado de la Casa" },
    { id: "b9", pt: "Vinho Verde", en: "Vinho Verde (Light Sparkling White)", es: "Vinho Verde" },
    { id: "b10", pt: "Espumante Brut", en: "Sparkling Brut", es: "Espumoso Brut" },
    { id: "b11", pt: "Champagne", en: "Champagne", es: "Champán" },
    { id: "b12", pt: "Água Tónica", en: "Tonic Water", es: "Agua Tónica" },
    { id: "b13", pt: "Chá Gelado de Limão", en: "Iced Lemon Tea", es: "Té Helado de Limón" },
    { id: "b14", pt: "Sumo de Maçã", en: "Apple Juice", es: "Zumo de Manzana" },
    { id: "b15", pt: "Café Expresso", en: "Espresso Coffee", es: "Café Expreso" },
    { id: "b16", pt: "Chá Verde", en: "Green Tea", es: "Té Verde" },
    { id: "b17", pt: "Gin Tónico", en: "Gin & Tonic", es: "Gin Tonic" },
    { id: "b18", pt: "Mojito", en: "Mojito", es: "Mojito" },
    { id: "b19", pt: "Whisky", en: "Whisky", es: "Whisky" },
    { id: "b20", pt: "Água de Coco", en: "Coconut Water", es: "Agua de Coco" },
  ],
};

// Flat lookup of every dish/drink by id, e.g. ALL_ITEMS["p3"] -> the Beef
// Tenderloin entry. Built once at load time so the rest of the app never has
// to search through MENU_POOL's category arrays to resolve an id to a name.
const ALL_ITEMS = {};
Object.values(MENU_POOL).forEach((list) => list.forEach((item) => (ALL_ITEMS[item.id] = item)));

// First names used for the "guests" at the table, one pool per language, each
// tagged with a gender ("f"/"m") so buildTable() can pair the name with a
// matching illustrated portrait from AVATARS below. If a table needs more guests than
// a pool has names, app.js cycles through the list again with a number suffix.
const GUEST_NAMES = {
  pt: [
    { name: "Ana", g: "f" }, { name: "Rui", g: "m" }, { name: "Carla", g: "f" }, { name: "João", g: "m" },
    { name: "Mariana", g: "f" }, { name: "Pedro", g: "m" }, { name: "Beatriz", g: "f" }, { name: "Tiago", g: "m" },
    { name: "Inês", g: "f" }, { name: "Miguel", g: "m" }, { name: "Sofia", g: "f" }, { name: "André", g: "m" },
  ],
  en: [
    { name: "Emma", g: "f" }, { name: "Liam", g: "m" }, { name: "Olivia", g: "f" }, { name: "Noah", g: "m" },
    { name: "Ava", g: "f" }, { name: "Ethan", g: "m" }, { name: "Sophia", g: "f" }, { name: "Mason", g: "m" },
    { name: "Isla", g: "f" }, { name: "Jack", g: "m" }, { name: "Grace", g: "f" }, { name: "Leo", g: "m" },
  ],
  es: [
    { name: "Lucía", g: "f" }, { name: "Mateo", g: "m" }, { name: "Sofía", g: "f" }, { name: "Diego", g: "m" },
    { name: "Valentina", g: "f" }, { name: "Javier", g: "m" }, { name: "Elena", g: "f" }, { name: "Pablo", g: "m" },
    { name: "Carmen", g: "f" }, { name: "Hugo", g: "m" }, { name: "Marta", g: "f" }, { name: "Dario", g: "m" },
  ],
};

// Illustrated avatar pools, split by gender to match a guest's name (see
// GUEST_NAMES). Each table shuffles its own copy so portraits do not repeat
// unnecessarily within the same table. The renderer still supports emoji
// values so older saved sessions can resume safely.
const AVATARS = {
  f: ["assets/avatars/avatar2.webp?v=3", "assets/avatars/avatar3.webp?v=3", "assets/avatars/avatar5.webp?v=3", "assets/avatars/avatar7.webp?v=3"],
  m: ["assets/avatars/avatar1.webp?v=3", "assets/avatars/avatar4.webp?v=3", "assets/avatars/avatar6.webp?v=3", "assets/avatars/avatar8.webp?v=3", "assets/avatars/avatar9.webp?v=3", "assets/avatars/avatar10.webp?v=3"],
};

// BCP-47 locale code per UI language. Used for Intl date/time formatting
// (see formatDateLabel/renderDashboard in app.js) and, historically, for
// browser text-to-speech — the game now speaks with its own pre-recorded
// audio clips (see AUDIO_BASE/SPEECH_SEGMENTS below) so every visitor hears
// the exact same voice regardless of what's installed on their device.
const VOICE_LANG = { pt: "pt-PT", en: "en-US", es: "es-ES" };

// Folder holding the pre-recorded audio clips, one subfolder per language.
// Two kinds of clip live there: a dish/drink's own id (e.g. "p3.m4a", named
// after its MENU_POOL id) and the fixed "connector" phrases below (e.g.
// "conn_drink_intro.m4a"). Generated once via the macOS `say` command from
// data.js's own content (see the note in README.md) — nothing here is
// generated at runtime.
const AUDIO_BASE = "assets/audio";

// Voice profiles are assigned once when a table is created and stay attached
// to that guest for the whole service. `folder` is the future location of a
// complete recorded voice set, e.g. assets/audio/pt/female_01/p3.m4a.
// Set `recorded` to true after that folder has all menu and connector clips;
// until then the player uses the existing language-level recordings and the
// profile's subtle pacing, so this release remains fully backwards compatible.
const VOICE_PROFILES = {
  pt: [
    { id: "pt_avatar_01", avatarIndex: 1, gender: "m", folder: "avatar_01", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_02", avatarIndex: 2, gender: "f", folder: "avatar_02", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_03", avatarIndex: 3, gender: "f", folder: "avatar_03", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_04", avatarIndex: 4, gender: "m", folder: "avatar_04", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_05", avatarIndex: 5, gender: "f", folder: "avatar_05", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_06", avatarIndex: 6, gender: "m", folder: "avatar_06", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_07", avatarIndex: 7, gender: "f", folder: "avatar_07", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_08", avatarIndex: 8, gender: "m", folder: "avatar_08", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_09", avatarIndex: 9, gender: "m", folder: "avatar_09", format: "mp3", playbackRate: 1, recorded: true },
    { id: "pt_avatar_10", avatarIndex: 10, gender: "m", folder: "avatar_10", format: "mp3", playbackRate: 1, recorded: true },
  ],
  en: [
    { id: "en_avatar_01", avatarIndex: 1, gender: "m", folder: "avatar_01", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_02", avatarIndex: 2, gender: "f", folder: "avatar_02", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_03", avatarIndex: 3, gender: "f", folder: "avatar_03", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_04", avatarIndex: 4, gender: "m", folder: "avatar_04", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_05", avatarIndex: 5, gender: "f", folder: "avatar_05", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_06", avatarIndex: 6, gender: "m", folder: "avatar_06", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_07", avatarIndex: 7, gender: "f", folder: "avatar_07", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_08", avatarIndex: 8, gender: "m", folder: "avatar_08", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_09", avatarIndex: 9, gender: "m", folder: "avatar_09", format: "mp3", playbackRate: 1, recorded: true },
    { id: "en_avatar_10", avatarIndex: 10, gender: "m", folder: "avatar_10", format: "mp3", playbackRate: 1, recorded: true },
  ],
  es: [
    { id: "es_avatar_01", avatarIndex: 1, gender: "m", folder: "avatar_01", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_02", avatarIndex: 2, gender: "f", folder: "avatar_02", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_03", avatarIndex: 3, gender: "f", folder: "avatar_03", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_04", avatarIndex: 4, gender: "m", folder: "avatar_04", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_05", avatarIndex: 5, gender: "f", folder: "avatar_05", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_06", avatarIndex: 6, gender: "m", folder: "avatar_06", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_07", avatarIndex: 7, gender: "f", folder: "avatar_07", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_08", avatarIndex: 8, gender: "m", folder: "avatar_08", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_09", avatarIndex: 9, gender: "m", folder: "avatar_09", format: "mp3", playbackRate: 1, recorded: true },
    { id: "es_avatar_10", avatarIndex: 10, gender: "m", folder: "avatar_10", format: "mp3", playbackRate: 1, recorded: true },
  ],
};

// Which connector clip opens a "full order" line, chosen at speak time by
// the real time of day (see getGreetingClip() in app.js) so a guest greets
// the waiter appropriately whether it's morning, afternoon or night.
const GREETING_CLIPS = {
  morning: "conn_greet_morning",
  afternoon: "conn_greet_afternoon",
  evening: "conn_greet",
};

// Describes how to assemble the audio clip *sequence* for each queue step
// type, per language — this is the audio equivalent of SPEECH_TEMPLATES
// below. Each entry in a sequence is either:
//   { clip: "conn_x" }   — play that fixed connector-phrase clip
//   { field: "bebida" }  — play the guest's chosen dish's own clip
//   { greeting: true }   — play whichever GREETING_CLIPS entry fits right now
// buildAudioPlaylist() in app.js turns one of these arrays into a list of
// file URLs to play back-to-back.
const SPEECH_SEGMENTS = {
  pt: {
    bebida: [{ clip: "conn_drink_intro" }, { field: "bebida" }, { clip: "conn_drink_outro" }],
    entrada: [{ clip: "conn_entrada_intro" }, { field: "entrada" }],
    principalAcompanhamento: [
      { clip: "conn_principal_intro" }, { field: "principal" },
      { clip: "conn_principal_mid" }, { field: "acompanhamento" },
    ],
    sobremesa: [{ clip: "conn_sobremesa_intro" }, { field: "sobremesa" }],
    full: [
      { greeting: true },
      { clip: "conn_drink_intro" }, { field: "bebida" }, { clip: "conn_drink_outro" },
      { clip: "conn_entrada_intro" }, { field: "entrada" },
      { clip: "conn_principal_intro" }, { field: "principal" },
      { clip: "conn_principal_mid" }, { field: "acompanhamento" },
      { clip: "conn_sobremesa_intro" }, { field: "sobremesa" },
    ],
  },
  en: {
    bebida: [{ clip: "conn_drink_intro" }, { field: "bebida" }, { clip: "conn_drink_outro" }],
    entrada: [{ clip: "conn_entrada_intro" }, { field: "entrada" }],
    principalAcompanhamento: [
      { clip: "conn_principal_intro" }, { field: "principal" },
      { clip: "conn_principal_mid" }, { field: "acompanhamento" },
    ],
    sobremesa: [{ clip: "conn_sobremesa_intro" }, { field: "sobremesa" }],
    full: [
      { greeting: true },
      { clip: "conn_drink_intro" }, { field: "bebida" }, { clip: "conn_drink_outro" },
      { clip: "conn_entrada_intro" }, { field: "entrada" },
      { clip: "conn_principal_intro" }, { field: "principal" },
      { clip: "conn_principal_mid" }, { field: "acompanhamento" },
      { clip: "conn_sobremesa_intro" }, { field: "sobremesa" },
    ],
  },
  es: {
    bebida: [{ clip: "conn_drink_intro" }, { field: "bebida" }, { clip: "conn_drink_outro" }],
    entrada: [{ clip: "conn_entrada_intro" }, { field: "entrada" }],
    principalAcompanhamento: [
      { clip: "conn_principal_intro" }, { field: "principal" },
      { clip: "conn_principal_mid" }, { field: "acompanhamento" },
    ],
    sobremesa: [{ clip: "conn_sobremesa_intro" }, { field: "sobremesa" }],
    full: [
      { greeting: true },
      { clip: "conn_drink_intro" }, { field: "bebida" }, { clip: "conn_drink_outro" },
      { clip: "conn_entrada_intro" }, { field: "entrada" },
      { clip: "conn_principal_intro" }, { field: "principal" },
      { clip: "conn_principal_mid" }, { field: "acompanhamento" },
      { clip: "conn_sobremesa_intro" }, { field: "sobremesa" },
    ],
  },
};

// Text version of the exact same lines, kept in lockstep with
// SPEECH_SEGMENTS above (same wording, same order) so the "reveal text"
// button always shows what was actually played. `greeting` is the
// already-resolved greeting string (see greetingText() in app.js) since a
// plain template literal can't know the time of day itself.
const SPEECH_TEMPLATES = {
  pt: {
    bebida: (b) => `Para mim, para beber, ${b}, por favor.`,
    entrada: (e) => `Como entrada, vou querer ${e}.`,
    principal: (p, a) => `Como prato principal, vou querer ${p}, acompanhado de ${a}.`,
    sobremesa: (s) => `De sobremesa, vou querer ${s}.`,
    full: (n, greeting) => `${greeting} Para mim, para beber, ${n.bebida}, por favor. Como entrada, vou querer ${n.entrada}. Como prato principal, vou querer ${n.principal}, acompanhado de ${n.acompanhamento}. De sobremesa, vou querer ${n.sobremesa}.`,
  },
  en: {
    bebida: (b) => `I'll have ${b} to drink, please.`,
    entrada: (e) => `For starters, I'll have the ${e}.`,
    principal: (p, a) => `For the main course, I'll have the ${p}, with ${a}.`,
    sobremesa: (s) => `For dessert, I'll have the ${s}.`,
    full: (n, greeting) => `${greeting} I'll have ${n.bebida} to drink, please. For starters, I'll have the ${n.entrada}. For the main course, I'll have the ${n.principal}, with ${n.acompanhamento}. For dessert, I'll have the ${n.sobremesa}.`,
  },
  es: {
    bebida: (b) => `Para beber, quiero ${b}, por favor.`,
    entrada: (e) => `De entrada, quiero ${e}.`,
    principal: (p, a) => `De principal, quiero ${p}, con ${a}.`,
    sobremesa: (s) => `De postre, quiero ${s}.`,
    full: (n, greeting) => `${greeting} Para beber, quiero ${n.bebida}, por favor. De entrada, quiero ${n.entrada}. De principal, quiero ${n.principal}, con ${n.acompanhamento}. De postre, quiero ${n.sobremesa}.`,
  },
};

// Natural wording assigned permanently to avatar 1..10. The generator uses
// the same rows to record different connector clips inside each avatar's
// folder, so the ten guests do not sound as if they are reading one script.
const SPEECH_PHRASES = {
  pt: [
    ["Para mim, para beber,", "por favor.", "Como entrada, vou querer", "Como prato principal, vou querer", "acompanhado de", "De sobremesa, vou querer"],
    ["Olá, tudo bem? Queria", "para beber.", "Para começar, escolho", "Depois quero", "com", "E termino com"],
    ["Quero", "se faz favor.", "Vou começar com", "Para mim será", "e", "No final,"],
    ["Pode trazer-me", "para beber?", "De entrada, fico com", "A seguir quero", "com", "Para sobremesa, escolho"],
    ["Para beber pode ser", "por favor.", "Quero", "O meu principal é", "acompanhado por", "Depois quero"],
    ["Eu fico com", "para beber.", "Peço", "Vou escolher", "com", "E de sobremesa,"],
    ["Traga-me", "para beber, por favor.", "Para começar quero", "Depois será", "acompanhado de", "Para acabar,"],
    ["Começo com", "para beber.", "Como entrada, escolho", "De principal quero", "com", "Para finalizar,"],
    ["Pode ser", "obrigado.", "Para entrada, queria", "Depois vou querer", "e", "Acabo com"],
    ["Gostaria de", "para beber.", "Primeiro quero", "A seguir escolho", "com", "Por último,"],
  ],
  en: [
    ["I'll have", "to drink, please.", "For starters, I'll have the", "For the main course, I'll have the", "with", "For dessert, I'll have the"],
    ["Hello. Could I have", "to drink?", "I'll start with the", "Then I'd like the", "with", "And to finish, the"],
    ["I'd like", "please.", "To begin, I'll choose the", "My main will be the", "and", "Finally, the"],
    ["Could you bring me", "to drink?", "For my starter, the", "Next, I'll have the", "with", "For dessert, the"],
    ["To drink, I'll take", "please.", "I'll begin with the", "My main course is the", "served with", "After that, the"],
    ["I'll go with", "to drink.", "First, the", "I'll choose the", "with", "And for dessert, the"],
    ["Please bring me", "to drink.", "I'd like the", "Then the", "accompanied by", "To end, the"],
    ["I'll start with", "to drink.", "For the starter, the", "For my main, the", "with", "To finish, the"],
    ["I'll take", "thank you.", "For starters, I'd like the", "Then I'll have the", "and", "I'll finish with the"],
    ["May I have", "to drink?", "First, I'll have the", "Next, I choose the", "with", "Lastly, the"],
  ],
  es: [
    ["Para beber, quiero", "por favor.", "De entrada, quiero", "De principal, quiero", "con", "De postre, quiero"],
    ["Hola, ¿qué tal? Quería", "para beber.", "Para empezar, elijo", "Después quiero", "con", "Y termino con"],
    ["Quiero", "por favor.", "Voy a empezar con", "Para mí será", "y", "Al final,"],
    ["¿Me trae", "para beber?", "De entrada, me quedo con", "A continuación quiero", "con", "Para el postre, elijo"],
    ["Para beber puede ser", "por favor.", "Quiero", "Mi principal es", "acompañado de", "Después quiero"],
    ["Me quedo con", "para beber.", "Pido", "Voy a elegir", "con", "Y de postre,"],
    ["Tráigame", "para beber, por favor.", "Para comenzar quiero", "Después será", "acompañado de", "Para terminar,"],
    ["Empiezo con", "para beber.", "Como entrante, elijo", "De principal quiero", "con", "Para finalizar,"],
    ["Puede ser", "gracias.", "De entrada, quería", "Después voy a querer", "y", "Termino con"],
    ["Me gustaría", "para beber.", "Primero quiero", "A continuación elijo", "con", "Por último,"],
  ],
};

const SPEECH_VARIANTS = Object.fromEntries(Object.entries(SPEECH_PHRASES).map(([lang, rows]) => [
  lang,
  rows.map(([drinkIntro, drinkOutro, starterIntro, mainIntro, mainMid, dessertIntro]) => ({
    bebida: (b) => `${drinkIntro} ${b} ${drinkOutro}`,
    entrada: (e) => `${starterIntro} ${e}.`,
    principal: (p, a) => `${mainIntro} ${p}, ${mainMid} ${a}.`,
    sobremesa: (s) => `${dessertIntro} ${s}.`,
    full: (n, greeting) => `${greeting} ${drinkIntro} ${n.bebida} ${drinkOutro} ${starterIntro} ${n.entrada}. ${mainIntro} ${n.principal}, ${mainMid} ${n.acompanhamento}. ${dessertIntro} ${n.sobremesa}.`,
  })),
]));

// Text shown by the greeting clips, used only for the "reveal text" feature
// (the greeting clip itself is picked by getGreetingClip() in app.js).
const GREETING_TEXT = {
  pt: { morning: "Bom dia.", afternoon: "Boa tarde.", evening: "Boa noite." },
  en: { morning: "Good morning.", afternoon: "Good afternoon.", evening: "Good evening." },
  es: { morning: "Buenos días.", afternoon: "Buenas tardes.", evening: "Buenas noches." },
};

// Minimum number of dishes the player must keep selected per category when
// hand-building a custom menu (see the menu builder screen in app.js).
// Prevents publishing a table with, say, zero starters to choose from.
const MENU_MIN = { entrada: 3, principal: 3, acompanhamento: 2, sobremesa: 2, bebida: 2 };

// Material Symbols icon name shown next to each menu category, reused by the
// sidebar menu, the menu builder and the per-guest order chips so the same
// category always looks the same everywhere.
const CATEGORY_ICONS = {
  entrada: "restaurant",
  principal: "dinner_dining",
  acompanhamento: "flatware",
  sobremesa: "icecream",
  bebida: "local_bar",
};

// Gradual practice modes available from the main setup screen.
const TRAINING_FOCUS = {
  complete: ["bebida", "entrada", "principal", "acompanhamento", "sobremesa"],
  drinks: ["bebida"],
  starters: ["entrada"],
  mains: ["principal", "acompanhamento"],
};

const DIFFICULTIES = {
  beginner: { menuSize: 4, maxReplays: Infinity, allowReveal: true, xpMultiplier: 0.8 },
  normal: { menuSize: 6, maxReplays: Infinity, allowReveal: true, xpMultiplier: 1 },
  hard: { menuSize: 8, maxReplays: 1, allowReveal: false, xpMultiplier: 1.25 },
  expert: { menuSize: 10, maxReplays: 0, allowReveal: false, xpMultiplier: 1.5 },
};

// Achievement definitions for the Dashboard. `id` matches the key returned
// by computeBadges() in app.js (which decides whether each one is unlocked),
// `icon` is the Material Symbols glyph shown in its badge circle. Titles and
// descriptions live in UI[lang] below, keyed as `badge<Id>Title`/`Desc`.
const BADGES = [
  { id: "firstService", icon: "room_service", tier: "bronze" },
  { id: "elephant", icon: "emoji_events", tier: "gold" },
  { id: "sommelier", icon: "wine_bar", tier: "silver" },
  { id: "agile", icon: "bolt", tier: "silver" },
  { id: "cartmaster", icon: "star", tier: "silver" },
  { id: "gourmet", icon: "restaurant", tier: "gold" },
  { id: "brigade", icon: "groups", tier: "silver" },
  { id: "perfectFive", icon: "workspace_premium", tier: "gold" },
  { id: "polyglot", icon: "translate", tier: "gold" },
  { id: "rushMaster", icon: "timer", tier: "gold" },
  { id: "confusionProof", icon: "psychology", tier: "gold" },
  { id: "careerGraduate", icon: "school", tier: "gold" },
];

// Progressive Career path. Copy lives in UI below; these records only hold
// rules, so the same mission works in all three interface languages.
const CAREER_MISSIONS = [
  { id: "first_shift", icon: "room_service", titleKey: "careerM1Title", descKey: "careerM1Desc", people: 2, orderStyle: "full", recap: true, minPct: 60, bonusXp: 50 },
  { id: "drinks_round", icon: "local_bar", titleKey: "careerM2Title", descKey: "careerM2Desc", people: 3, orderStyle: "byCourse", recap: true, minPct: 65, bonusXp: 70 },
  { id: "lunch_service", icon: "restaurant", titleKey: "careerM3Title", descKey: "careerM3Desc", people: 4, orderStyle: "random", recap: true, minPct: 70, bonusXp: 90 },
  { id: "no_notes", icon: "edit_off", titleKey: "careerM4Title", descKey: "careerM4Desc", people: 4, orderStyle: "full", recap: false, minPct: 75, bonusXp: 110 },
  { id: "busy_room", icon: "groups", titleKey: "careerM5Title", descKey: "careerM5Desc", people: 6, orderStyle: "byCourse", recap: true, minPct: 75, bonusXp: 140 },
  { id: "precision", icon: "target", titleKey: "careerM6Title", descKey: "careerM6Desc", people: 5, orderStyle: "random", recap: false, minPct: 85, bonusXp: 170 },
  { id: "rush_hour", icon: "timer", titleKey: "careerM7Title", descKey: "careerM7Desc", people: 6, orderStyle: "full", recap: false, minPct: 80, maxSeconds: 240, bonusXp: 210 },
  { id: "banquet", icon: "celebration", titleKey: "careerM8Title", descKey: "careerM8Desc", people: 8, orderStyle: "byCourse", recap: false, minPct: 80, bonusXp: 260 },
  { id: "maitre_test", icon: "workspace_premium", titleKey: "careerM9Title", descKey: "careerM9Desc", people: 10, orderStyle: "random", recap: false, minPct: 90, bonusXp: 350 },
];

// All interface copy, one object per supported language. `t()` in app.js
// returns `UI[state.lang]`, so every screen just reads `s.someKey` instead
// of branching on the current language. Values that need to embed a
// variable (a count, a name, a computed percentage) are functions instead
// of plain strings — call them with the value to interpolate.
// The three language blocks below (pt/en/es) all have the exact same set of
// keys; keep them in sync when adding new copy.
const UI = {
  pt: {
    appTitle: "Mesa Cheia",
    appSubtitle: "Treino de memória para empregados de mesa",
    welcomeText: "Bem-vindo! Este é um jogo de treino de memória para empregados de mesa: vais ouvir o pedido de cada pessoa à mesa e depois terás de o registar de cabeça — sem apontar nada no papel. Ajusta as opções abaixo e começa a tua primeira mesa.",
    footerCredit: "Criado por Alberto Junior, estudante de Engenharia Informática e de Computadores, com a ajuda da IA.",
    footerTagline: "Treino profissional de memória para sala",
    setupPeople: "Quantas pessoas na mesa?",
    setupLang: "Idioma da mesa",
    setupRecap: "Rever as respostas antes da avaliação final",
    recapHelp: "Mostra um resumo do que registaste e permite corrigir antes de veres a pontuação. Não volta a reproduzir o áudio.",
    difficultyLabel: "Dificuldade",
    difficultyBeginner: "Iniciante", difficultyNormal: "Normal", difficultyHard: "Difícil", difficultyExpert: "Especialista",
    difficultyHelpBeginner: "Menu reduzido, texto disponível e repetições ilimitadas.",
    difficultyHelpNormal: "Menu equilibrado, texto disponível e repetições ilimitadas.",
    difficultyHelpHard: "Menu maior, sem revelar texto e apenas uma repetição manual.",
    difficultyHelpExpert: "Menu completo, sem texto e sem repetições manuais.",
    similarOrdersLabel: "Incluir pedidos semelhantes",
    similarOrdersHelp: "Cria pares de clientes com pedidos quase iguais para treinar associações difíceis.",
    rushHourLabel: "Ativar Rush Hour",
    rushHourHelp: "Tens um tempo limite ajustado ao tamanho da mesa; o contador começa com o atendimento.",
    rushTime: (time) => `Rush Hour: ${time}`,
    timeExpired: "O tempo terminou — regista agora o que conseguiste memorizar.",
    replayLimit: "Limite de repetições atingido",
    orderStyleLabel: "Como o pedido é tirado?",
    orderStyleRandom: "Aleatório (recomendado)",
    orderStyleFull: "Pedido completo por pessoa",
    orderStyleByCourse: "Por curso (entradas → principais → sobremesas)",
    trainingFocusLabel: "O que queres treinar?",
    trainingFocusComplete: "Pedido completo",
    trainingFocusDrinks: "Só bebidas",
    trainingFocusStarters: "Só entradas",
    trainingFocusMains: "Prato principal + acompanhamento",
    startButton: "Nova Mesa",
    muteLabel: "Silenciar voz",
    unmuteLabel: "Ativar voz",
    menuModeLabel: "Como definir o menu de hoje?",
    menuModeRandom: "Aleatório (recomendado)",
    menuModeCustom: "Escolher os pratos",
    menuBuilderTitle: "Monta o menu de hoje",
    menuBuilderHint: "Escolhe os pratos que vão estar disponíveis nesta mesa.",
    selectAllBtn: "Selecionar todos",
    clearAllBtn: "Limpar",
    backBtn: "Voltar",
    confirmMenuBtn: "Começar Mesa",
    minWarning: (min) => `escolhe pelo menos ${min}`,
    menuTitle: "Menu de hoje",
    catEntrada: "Entradas",
    catPrincipal: "Principais",
    catAcompanhamento: "Acompanhamentos",
    catSobremesa: "Sobremesas",
    catBebida: "Bebidas",
    modeRounds: "Modo: por rondas",
    modePerson: "Modo: pessoa a pessoa",
    orderTitle: "A tirar o pedido",
    listen: "Ouvir",
    reveal: "Ver o que disse",
    hide: "Esconder texto",
    next: "Seguinte",
    exitTable: "Sair",
    exitConfirmMsg: "Isto não vai ser gravado no teu histórico. Tens a certeza que queres sair desta mesa?",
    exitCancel: "Cancelar",
    exitLeave: "Sim, sair",
    readyMsg: "A mesa está pronta. Quando estiveres preparado, começa o atendimento.",
    startServiceBtn: "Começar Atendimento",
    askingFor: (name) => `${name} está a falar...`,
    fieldLabel: {
      bebida: "bebida",
      entrada: "entrada",
      principalAcompanhamento: "prato principal",
      sobremesa: "sobremesa",
      full: "pedido completo",
    },
    registerTitle: "Regista o pedido no sistema",
    registerHint: "Sem espreitar — regista de memória o que cada pessoa pediu.",
    selectPlaceholder: "-- selecionar --",
    confirmOrder: "Confirmar Pedido",
    recapTitle: "Última chamada: confere o pedido da mesa",
    recapHint: "Antes de sair da mesa, relê o que registaste para cada pessoa.",
    recapConfirm: "Está tudo certo, fechar mesa",
    recapEdit: "Voltar a corrigir",
    resultsTitle: "Resultado",
    correct: "Correto",
    wrong: "Errado",
    theyOrdered: "O pedido real era:",
    youRegistered: "Registaste:",
    scoreLabel: "Pontuação",
    newTable: "Nova Mesa",
    person: "Pessoa",
    navTraining: "Treino",
    navDashboard: "Dashboard",
    dashboardTitle: "Painel de Performance",
    dashboardSubtitle: "A tua jornada rumo à excelência no serviço.",
    startTrainingCta: "Iniciar Treino",
    statAccuracy: "Taxa de Precisão",
    statStreak: "Dias Consecutivos",
    statStreakRecord: (n) => `Recorde: ${n} dias`,
    statTotalTables: "Mesas Atendidas",
    statMemberSince: (d) => `Membro desde ${d}`,
    sectionMemoryStrength: "Força da Memória",
    memoryHint: "Sem dados suficientes ainda — treina mais para revelar os teus pontos fortes.",
    sectionRecentActivity: "Atividade Recente",
    noActivity: "Ainda não fechaste nenhuma mesa. Vai a Treino para começar.",
    sectionBadges: "Conquistas & Distintivos",
    sectionPerformanceTrend: "Evolução da precisão",
    sectionPerformanceInsights: "Resumo de desempenho",
    sectionLanguageStats: "Desempenho por idioma",
    sectionDifficultyStats: "Desempenho por dificuldade",
    statBestScore: "Melhor precisão", statGuestsServed: "Clientes atendidos", statAverageTable: "Média por mesa", statTotalXp: "XP total",
    insightStrongest: "Categoria mais forte", insightWeakest: "A melhorar", insightBestCombo: "Melhor sequência", insightCareer: "Carreira concluída",
    noData: "Ainda sem dados suficientes.",
    gaugeDominated: "DOMINADO",
    gaugeGreat: "MUITO BOM",
    gaugeProgress: "EM PROGRESSO",
    gaugePractice: "PRECISA TREINAR",
    minutesShort: (n) => `${n} min`,
    tableSummary: (n, mode) => `Mesa de ${n} — ${mode === "rounds" ? "por rondas" : "pessoa a pessoa"}`,
    progressionTitle: "Progressão profissional",
    resetProgress: "Reiniciar XP",
    resetProgressConfirm: "Queres mesmo reiniciar o XP, o nível e o título? O histórico e as estatísticas serão mantidos.",
    levelWord: "Nível",
    levelShort: (n) => `N. ${n}`,
    levelLabel: (n) => `Nível ${n}`,
    currentTitle: "Título atual",
    xpUntilNext: (xp, level) => `${xp} XP até ao nível ${level}`,
    maxLevel: "Nível máximo alcançado",
    levelUp: (level, title) => `Subiste para o nível ${level}: ${title}!`,
    xpBase: "Pedidos corretos",
    xpErrorPenalty: "Penalização por erros",
    xpAccuracyBonus: "Bónus de precisão",
    xpComboBonus: "Sequência de acertos",
    xpSpeedBonus: "Serviço rápido",
    xpLargeTableBonus: "Mesa grande",
    xpCareerBonus: "Bónus de Carreira",
    titleApprentice: "Aprendiz de Serviço",
    titleRunner: "Ajudante de Sala",
    titleCommis: "Commis de Sala",
    titleWaiter: "Empregado de Mesa",
    titleSenior: "Empregado Sénior",
    titleHeadWaiter: "Chefe de Turno",
    titleMaitre: "Maître",
    titleServiceExpert: "Especialista de Serviço",
    titleRestaurantMaster: "Mestre de Restaurante",
    titleLegend: "Lenda da Sala",
    navCareer: "Carreira",
    careerTitle: "Modo Carreira",
    careerSubtitle: "Avança por nove turnos, domina a sala e chega a Maître.",
    careerLanguage: "Idioma dos clientes",
    careerProgress: (done, total) => `${done} de ${total} missões concluídas`,
    careerLocked: "Conclui a missão anterior para desbloquear.",
    careerStart: "Começar desafio",
    careerReplay: "Repetir missão",
    careerContinue: "Voltar à Carreira",
    careerGoal: (pct) => `Meta: pelo menos ${pct}% de precisão`,
    careerTimeGoal: (min) => ` e concluir em até ${min} min`,
    careerBonus: (xp) => `Bónus da primeira conclusão: ${xp} XP`,
    careerComplete: "Missão concluída",
    careerFailed: "Missão não concluída",
    careerCompleteText: (stars) => `Conquistaste ${stars} ${stars === 1 ? "estrela" : "estrelas"} e desbloqueaste o próximo desafio.`,
    careerFailedText: (pct) => `Precisavas de atingir pelo menos ${pct}% de precisão. Tenta novamente.`,
    careerFailedTime: (min) => `A precisão foi suficiente, mas precisavas de terminar em até ${min} minutos.`,
    careerAllComplete: "Carreira concluída — conquistaste a sala!",
    careerM1Title: "Primeiro Turno", careerM1Desc: "Atende dois clientes e aprende o ritmo do serviço.",
    careerM2Title: "Ronda de Bebidas", careerM2Desc: "Organiza os pedidos por cursos numa mesa de três.",
    careerM3Title: "Serviço de Almoço", careerM3Desc: "Quatro clientes e um formato de pedido imprevisível.",
    careerM4Title: "Sem Segunda Oportunidade", careerM4Desc: "Fecha a mesa sem rever o pedido no final.",
    careerM5Title: "Sala Cheia", careerM5Desc: "Mantém o controlo de uma mesa movimentada de seis.",
    careerM6Title: "Precisão Profissional", careerM6Desc: "Sem recapitulativo e com uma meta de precisão elevada.",
    careerM7Title: "Rush Hour", careerM7Desc: "Equilibra rapidez e precisão sob pressão de tempo.",
    careerM8Title: "O Banquete", careerM8Desc: "Coordena oito clientes num serviço por rondas.",
    careerM9Title: "Prova de Maître", careerM9Desc: "Dez clientes, 90% de precisão e nenhuma ajuda.",
    badgeElephantTitle: "Memória de Elefante",
    badgeElephantDesc: "Faz uma mesa com 100% de acerto.",
    badgeSommelierTitle: "Sommelier em Treino",
    badgeSommelierDesc: "Atinge 90% de precisão em Bebidas (mín. 10 pedidos).",
    badgeAgileTitle: "Serviço Ágil",
    badgeAgileDesc: "Fecha uma mesa em menos de 3 minutos.",
    badgeCartmasterTitle: "Mestre de Carta",
    badgeCartmasterDesc: "Completa 10 mesas.",
    badgeGourmetTitle: "Expert Gourmet",
    badgeGourmetDesc: "Completa 25 mesas.",
    badgeBrigadeTitle: "Líder de Brigada",
    badgeBrigadeDesc: "Atende uma mesa com 8 ou mais pessoas.",
    badgeFirstServiceTitle: "Primeiro Serviço", badgeFirstServiceDesc: "Conclui a primeira mesa.",
    badgePerfectFiveTitle: "Cinco Estrelas", badgePerfectFiveDesc: "Conclui cinco mesas com 100% de precisão.",
    badgePolyglotTitle: "Sala Poliglota", badgePolyglotDesc: "Conclui mesas em português, inglês e espanhol.",
    badgeRushMasterTitle: "Mestre da Hora de Ponta", badgeRushMasterDesc: "Conclui um Rush Hour dentro do tempo.",
    badgeConfusionProofTitle: "À Prova de Confusão", badgeConfusionProofDesc: "Obtém pelo menos 90% num treino de pedidos semelhantes.",
    badgeCareerGraduateTitle: "Graduado da Academia", badgeCareerGraduateDesc: "Conclui as nove missões do Modo Carreira.",
  },
  en: {
    appTitle: "Full House",
    appSubtitle: "Memory training for waitstaff",
    welcomeText: "Welcome! This is a memory training game for waitstaff: you'll listen to each guest's order and then register it from memory — no notes allowed. Adjust the options below and start your first table.",
    footerCredit: "Created by Computer Engineering student Alberto Junior, with the help of AI.",
    footerTagline: "Professional dining-room memory training",
    setupPeople: "How many people at the table?",
    setupLang: "Table language",
    setupRecap: "Review your answers before final scoring",
    recapHelp: "Shows a summary of what you registered and lets you make corrections before seeing the score. It does not replay the audio.",
    difficultyLabel: "Difficulty",
    difficultyBeginner: "Beginner", difficultyNormal: "Normal", difficultyHard: "Hard", difficultyExpert: "Expert",
    difficultyHelpBeginner: "Smaller menu, reveal available and unlimited replays.",
    difficultyHelpNormal: "Balanced menu, reveal available and unlimited replays.",
    difficultyHelpHard: "Larger menu, no reveal and only one manual replay.",
    difficultyHelpExpert: "Full menu, no reveal and no manual replays.",
    similarOrdersLabel: "Include similar orders",
    similarOrdersHelp: "Creates pairs of guests with nearly identical orders to train difficult associations.",
    rushHourLabel: "Enable Rush Hour",
    rushHourHelp: "A time limit adapts to table size; the countdown starts with service.",
    rushTime: (time) => `Rush Hour: ${time}`,
    timeExpired: "Time is up — register what you managed to remember.",
    replayLimit: "Replay limit reached",
    orderStyleLabel: "How is the order taken?",
    orderStyleRandom: "Random (recommended)",
    orderStyleFull: "Full order per person",
    orderStyleByCourse: "By course (starters → mains → desserts)",
    trainingFocusLabel: "What do you want to practise?",
    trainingFocusComplete: "Full order",
    trainingFocusDrinks: "Drinks only",
    trainingFocusStarters: "Starters only",
    trainingFocusMains: "Main course + side",
    startButton: "New Table",
    muteLabel: "Mute voice",
    unmuteLabel: "Unmute voice",
    menuModeLabel: "How should today's menu be set?",
    menuModeRandom: "Random (recommended)",
    menuModeCustom: "Choose the dishes",
    menuBuilderTitle: "Build today's menu",
    menuBuilderHint: "Pick the dishes that will be available at this table.",
    selectAllBtn: "Select all",
    clearAllBtn: "Clear",
    backBtn: "Back",
    confirmMenuBtn: "Start Table",
    minWarning: (min) => `pick at least ${min}`,
    menuTitle: "Today's Menu",
    catEntrada: "Starters",
    catPrincipal: "Mains",
    catAcompanhamento: "Sides",
    catSobremesa: "Desserts",
    catBebida: "Drinks",
    modeRounds: "Mode: by rounds",
    modePerson: "Mode: person by person",
    orderTitle: "Taking the order",
    listen: "Listen",
    reveal: "See what they said",
    hide: "Hide text",
    next: "Next",
    exitTable: "Exit",
    exitConfirmMsg: "This won't be saved to your history. Are you sure you want to leave this table?",
    exitCancel: "Cancel",
    exitLeave: "Yes, exit",
    readyMsg: "The table is ready. Start the service whenever you are.",
    startServiceBtn: "Start Service",
    askingFor: (name) => `${name} is speaking...`,
    fieldLabel: {
      bebida: "drink",
      entrada: "starter",
      principalAcompanhamento: "main course",
      sobremesa: "dessert",
      full: "full order",
    },
    registerTitle: "Register the order in the system",
    registerHint: "No peeking — register from memory what each person ordered.",
    selectPlaceholder: "-- select --",
    confirmOrder: "Confirm Order",
    recapTitle: "Last call: check the table's order",
    recapHint: "Before leaving the table, re-read what you registered for each person.",
    recapConfirm: "All good, close the table",
    recapEdit: "Go back and fix",
    resultsTitle: "Results",
    correct: "Correct",
    wrong: "Wrong",
    theyOrdered: "The real order was:",
    youRegistered: "You registered:",
    scoreLabel: "Score",
    newTable: "New Table",
    person: "Person",
    navTraining: "Training",
    navDashboard: "Dashboard",
    dashboardTitle: "Performance Dashboard",
    dashboardSubtitle: "Your journey towards excellence in service.",
    startTrainingCta: "Start Training",
    statAccuracy: "Accuracy Rate",
    statStreak: "Day Streak",
    statStreakRecord: (n) => `Record: ${n} days`,
    statTotalTables: "Tables Served",
    statMemberSince: (d) => `Member since ${d}`,
    sectionMemoryStrength: "Memory Strength",
    memoryHint: "Not enough data yet — train more to reveal your strengths.",
    sectionRecentActivity: "Recent Activity",
    noActivity: "You haven't closed a table yet. Go to Training to start.",
    sectionBadges: "Achievements & Badges",
    sectionPerformanceTrend: "Accuracy trend",
    sectionPerformanceInsights: "Performance summary",
    sectionLanguageStats: "Performance by language",
    sectionDifficultyStats: "Performance by difficulty",
    statBestScore: "Best accuracy", statGuestsServed: "Guests served", statAverageTable: "Average table", statTotalXp: "Total XP",
    insightStrongest: "Strongest category", insightWeakest: "Needs work", insightBestCombo: "Best streak", insightCareer: "Career completed",
    noData: "Not enough data yet.",
    gaugeDominated: "MASTERED",
    gaugeGreat: "GREAT",
    gaugeProgress: "IN PROGRESS",
    gaugePractice: "NEEDS PRACTICE",
    minutesShort: (n) => `${n} min`,
    tableSummary: (n, mode) => `Table of ${n} — ${mode === "rounds" ? "by rounds" : "person by person"}`,
    progressionTitle: "Professional progression",
    resetProgress: "Reset XP",
    resetProgressConfirm: "Reset your XP, level and title? Your history and statistics will be kept.",
    levelWord: "Level",
    levelShort: (n) => `Lv. ${n}`,
    levelLabel: (n) => `Level ${n}`,
    currentTitle: "Current title",
    xpUntilNext: (xp, level) => `${xp} XP to level ${level}`,
    maxLevel: "Maximum level reached",
    levelUp: (level, title) => `Level up! Level ${level}: ${title}`,
    xpBase: "Correct orders",
    xpErrorPenalty: "Error penalty",
    xpAccuracyBonus: "Accuracy bonus",
    xpComboBonus: "Correct-answer streak",
    xpSpeedBonus: "Fast service",
    xpLargeTableBonus: "Large table",
    xpCareerBonus: "Career bonus",
    titleApprentice: "Service Apprentice",
    titleRunner: "Dining Room Runner",
    titleCommis: "Commis Waiter",
    titleWaiter: "Waiter",
    titleSenior: "Senior Waiter",
    titleHeadWaiter: "Head Waiter",
    titleMaitre: "Maître d'",
    titleServiceExpert: "Service Expert",
    titleRestaurantMaster: "Restaurant Master",
    titleLegend: "Dining Room Legend",
    navCareer: "Career",
    careerTitle: "Career Mode",
    careerSubtitle: "Progress through nine shifts, master the dining room and become a Maître d'.",
    careerLanguage: "Guest language",
    careerProgress: (done, total) => `${done} of ${total} missions completed`,
    careerLocked: "Complete the previous mission to unlock this one.",
    careerStart: "Start challenge",
    careerReplay: "Replay mission",
    careerContinue: "Back to Career",
    careerGoal: (pct) => `Goal: at least ${pct}% accuracy`,
    careerTimeGoal: (min) => ` and finish within ${min} min`,
    careerBonus: (xp) => `First-clear bonus: ${xp} XP`,
    careerComplete: "Mission complete",
    careerFailed: "Mission not completed",
    careerCompleteText: (stars) => `You earned ${stars} ${stars === 1 ? "star" : "stars"} and unlocked the next challenge.`,
    careerFailedText: (pct) => `You needed at least ${pct}% accuracy. Try again.`,
    careerFailedTime: (min) => `Your accuracy was high enough, but you needed to finish within ${min} minutes.`,
    careerAllComplete: "Career complete — you conquered the dining room!",
    careerM1Title: "First Shift", careerM1Desc: "Serve two guests and learn the rhythm of service.",
    careerM2Title: "Drinks Round", careerM2Desc: "Organize course-by-course orders at a table of three.",
    careerM3Title: "Lunch Service", careerM3Desc: "Four guests and an unpredictable order format.",
    careerM4Title: "No Second Chance", careerM4Desc: "Close the table without reviewing the order at the end.",
    careerM5Title: "Busy Dining Room", careerM5Desc: "Stay in control of a lively table of six.",
    careerM6Title: "Professional Precision", careerM6Desc: "No recap and a demanding accuracy target.",
    careerM7Title: "Rush Hour", careerM7Desc: "Balance speed and accuracy under time pressure.",
    careerM8Title: "The Banquet", careerM8Desc: "Coordinate eight guests in course-by-course service.",
    careerM9Title: "Maître d' Trial", careerM9Desc: "Ten guests, 90% accuracy and no assistance.",
    badgeElephantTitle: "Elephant Memory",
    badgeElephantDesc: "Complete a table with 100% accuracy.",
    badgeSommelierTitle: "Sommelier in Training",
    badgeSommelierDesc: "Reach 90% accuracy on Drinks (min. 10 orders).",
    badgeAgileTitle: "Agile Service",
    badgeAgileDesc: "Close a table in under 3 minutes.",
    badgeCartmasterTitle: "Menu Master",
    badgeCartmasterDesc: "Complete 10 tables.",
    badgeGourmetTitle: "Gourmet Expert",
    badgeGourmetDesc: "Complete 25 tables.",
    badgeBrigadeTitle: "Brigade Leader",
    badgeBrigadeDesc: "Serve a table with 8 or more people.",
    badgeFirstServiceTitle: "First Service", badgeFirstServiceDesc: "Complete your first table.",
    badgePerfectFiveTitle: "Five-Star Memory", badgePerfectFiveDesc: "Complete five tables with 100% accuracy.",
    badgePolyglotTitle: "Polyglot Dining Room", badgePolyglotDesc: "Complete tables in Portuguese, English and Spanish.",
    badgeRushMasterTitle: "Rush Hour Master", badgeRushMasterDesc: "Complete a Rush Hour within the time limit.",
    badgeConfusionProofTitle: "Confusion Proof", badgeConfusionProofDesc: "Score at least 90% in a similar-orders session.",
    badgeCareerGraduateTitle: "Academy Graduate", badgeCareerGraduateDesc: "Complete all nine Career missions.",
  },
  es: {
    appTitle: "Mesa Llena",
    appSubtitle: "Entrenamiento de memoria para camareros",
    welcomeText: "¡Bienvenido! Este es un juego de entrenamiento de memoria para camareros: escucharás el pedido de cada persona en la mesa y luego tendrás que registrarlo de memoria, sin apuntar nada. Ajusta las opciones y empieza tu primera mesa.",
    footerCredit: "Creado por Alberto Junior, estudiante de Ingeniería Informática y de Computadores, con la ayuda de la IA.",
    footerTagline: "Entrenamiento profesional de memoria para sala",
    recapHelp: "Muestra un resumen de lo registrado y permite corregirlo antes de ver la puntuación. No vuelve a reproducir el audio.",
    difficultyLabel: "Dificultad",
    difficultyBeginner: "Principiante", difficultyNormal: "Normal", difficultyHard: "Difícil", difficultyExpert: "Experto",
    difficultyHelpBeginner: "Menú reducido, texto disponible y repeticiones ilimitadas.",
    difficultyHelpNormal: "Menú equilibrado, texto disponible y repeticiones ilimitadas.",
    difficultyHelpHard: "Menú mayor, sin mostrar texto y una sola repetición manual.",
    difficultyHelpExpert: "Menú completo, sin texto y sin repeticiones manuales.",
    similarOrdersLabel: "Incluir pedidos similares",
    similarOrdersHelp: "Crea parejas de clientes con pedidos casi iguales para entrenar asociaciones difíciles.",
    rushHourLabel: "Activar Hora Punta",
    rushHourHelp: "El tiempo límite se adapta al tamaño de la mesa y empieza con el servicio.",
    rushTime: (time) => `Hora Punta: ${time}`,
    timeExpired: "Se acabó el tiempo — registra ahora lo que hayas memorizado.",
    replayLimit: "Límite de repeticiones alcanzado",
    setupPeople: "¿Cuántas personas hay en la mesa?",
    setupLang: "Idioma de la mesa",
    setupRecap: "Revisar las respuestas antes de la evaluación final",
    orderStyleLabel: "¿Cómo se toma el pedido?",
    orderStyleRandom: "Aleatorio (recomendado)",
    orderStyleFull: "Pedido completo por persona",
    orderStyleByCourse: "Por curso (entrantes → principales → postres)",
    trainingFocusLabel: "¿Qué quieres practicar?",
    trainingFocusComplete: "Pedido completo",
    trainingFocusDrinks: "Solo bebidas",
    trainingFocusStarters: "Solo entrantes",
    trainingFocusMains: "Principal + guarnición",
    startButton: "Nueva Mesa",
    muteLabel: "Silenciar voz",
    unmuteLabel: "Activar voz",
    menuModeLabel: "¿Cómo definir el menú de hoy?",
    menuModeRandom: "Aleatorio (recomendado)",
    menuModeCustom: "Elegir los platos",
    menuBuilderTitle: "Arma el menú de hoy",
    menuBuilderHint: "Elige los platos que estarán disponibles en esta mesa.",
    selectAllBtn: "Seleccionar todo",
    clearAllBtn: "Limpiar",
    backBtn: "Volver",
    confirmMenuBtn: "Empezar Mesa",
    minWarning: (min) => `elige al menos ${min}`,
    menuTitle: "Menú de hoy",
    catEntrada: "Entrantes",
    catPrincipal: "Principales",
    catAcompanhamento: "Guarniciones",
    catSobremesa: "Postres",
    catBebida: "Bebidas",
    modeRounds: "Modo: por rondas",
    modePerson: "Modo: persona por persona",
    orderTitle: "Tomando el pedido",
    listen: "Escuchar",
    reveal: "Ver lo que dijo",
    hide: "Ocultar texto",
    next: "Siguiente",
    exitTable: "Salir",
    exitConfirmMsg: "Esto no se guardará en tu historial. ¿Seguro que quieres salir de esta mesa?",
    exitCancel: "Cancelar",
    exitLeave: "Sí, salir",
    readyMsg: "La mesa está lista. Empieza el servicio cuando quieras.",
    startServiceBtn: "Empezar Servicio",
    askingFor: (name) => `${name} está hablando...`,
    fieldLabel: {
      bebida: "bebida",
      entrada: "entrante",
      principalAcompanhamento: "plato principal",
      sobremesa: "postre",
      full: "pedido completo",
    },
    registerTitle: "Registra el pedido en el sistema",
    registerHint: "Sin espiar — registra de memoria lo que pidió cada persona.",
    selectPlaceholder: "-- seleccionar --",
    confirmOrder: "Confirmar Pedido",
    recapTitle: "Última llamada: revisa el pedido de la mesa",
    recapHint: "Antes de dejar la mesa, vuelve a leer lo que registraste para cada persona.",
    recapConfirm: "Todo correcto, cerrar mesa",
    recapEdit: "Volver a corregir",
    resultsTitle: "Resultado",
    correct: "Correcto",
    wrong: "Incorrecto",
    theyOrdered: "El pedido real era:",
    youRegistered: "Registraste:",
    scoreLabel: "Puntuación",
    newTable: "Nueva Mesa",
    person: "Persona",
    navTraining: "Entrenamiento",
    navDashboard: "Dashboard",
    dashboardTitle: "Panel de Rendimiento",
    dashboardSubtitle: "Tu camino hacia la excelencia en el servicio.",
    startTrainingCta: "Empezar Entrenamiento",
    statAccuracy: "Tasa de Precisión",
    statStreak: "Días Consecutivos",
    statStreakRecord: (n) => `Récord: ${n} días`,
    statTotalTables: "Mesas Atendidas",
    statMemberSince: (d) => `Miembro desde ${d}`,
    sectionMemoryStrength: "Fuerza de Memoria",
    memoryHint: "Aún no hay suficientes datos — entrena más para revelar tus puntos fuertes.",
    sectionRecentActivity: "Actividad Reciente",
    noActivity: "Todavía no has cerrado ninguna mesa. Ve a Entrenamiento para empezar.",
    sectionBadges: "Logros y Distintivos",
    sectionPerformanceTrend: "Evolución de la precisión",
    sectionPerformanceInsights: "Resumen de rendimiento",
    sectionLanguageStats: "Rendimiento por idioma",
    sectionDifficultyStats: "Rendimiento por dificultad",
    statBestScore: "Mejor precisión", statGuestsServed: "Clientes atendidos", statAverageTable: "Media por mesa", statTotalXp: "XP total",
    insightStrongest: "Categoría más fuerte", insightWeakest: "A mejorar", insightBestCombo: "Mejor racha", insightCareer: "Carrera completada",
    noData: "Aún no hay datos suficientes.",
    gaugeDominated: "DOMINADO",
    gaugeGreat: "MUY BIEN",
    gaugeProgress: "EN PROGRESO",
    gaugePractice: "NECESITA PRÁCTICA",
    minutesShort: (n) => `${n} min`,
    tableSummary: (n, mode) => `Mesa de ${n} — ${mode === "rounds" ? "por rondas" : "persona a persona"}`,
    progressionTitle: "Progresión profesional",
    resetProgress: "Reiniciar XP",
    resetProgressConfirm: "¿Quieres reiniciar el XP, el nivel y el título? Se conservarán el historial y las estadísticas.",
    levelWord: "Nivel",
    levelShort: (n) => `N. ${n}`,
    levelLabel: (n) => `Nivel ${n}`,
    currentTitle: "Título actual",
    xpUntilNext: (xp, level) => `${xp} XP hasta el nivel ${level}`,
    maxLevel: "Nivel máximo alcanzado",
    levelUp: (level, title) => `¡Has subido al nivel ${level}: ${title}!`,
    xpBase: "Pedidos correctos",
    xpErrorPenalty: "Penalización por errores",
    xpAccuracyBonus: "Bonus de precisión",
    xpComboBonus: "Racha de aciertos",
    xpSpeedBonus: "Servicio rápido",
    xpLargeTableBonus: "Mesa grande",
    xpCareerBonus: "Bonus de Carrera",
    titleApprentice: "Aprendiz de Servicio",
    titleRunner: "Ayudante de Sala",
    titleCommis: "Commis de Sala",
    titleWaiter: "Camarero",
    titleSenior: "Camarero Sénior",
    titleHeadWaiter: "Jefe de Turno",
    titleMaitre: "Maître",
    titleServiceExpert: "Especialista de Servicio",
    titleRestaurantMaster: "Maestro de Restaurante",
    titleLegend: "Leyenda de la Sala",
    navCareer: "Carrera",
    careerTitle: "Modo Carrera",
    careerSubtitle: "Avanza por nueve turnos, domina la sala y conviértete en Maître.",
    careerLanguage: "Idioma de los clientes",
    careerProgress: (done, total) => `${done} de ${total} misiones completadas`,
    careerLocked: "Completa la misión anterior para desbloquearla.",
    careerStart: "Empezar desafío",
    careerReplay: "Repetir misión",
    careerContinue: "Volver a Carrera",
    careerGoal: (pct) => `Meta: al menos ${pct}% de precisión`,
    careerTimeGoal: (min) => ` y terminar en hasta ${min} min`,
    careerBonus: (xp) => `Bonus de primera victoria: ${xp} XP`,
    careerComplete: "Misión completada",
    careerFailed: "Misión no completada",
    careerCompleteText: (stars) => `Has conseguido ${stars} ${stars === 1 ? "estrella" : "estrellas"} y desbloqueado el siguiente desafío.`,
    careerFailedText: (pct) => `Necesitabas al menos un ${pct}% de precisión. Inténtalo de nuevo.`,
    careerFailedTime: (min) => `La precisión fue suficiente, pero debías terminar en hasta ${min} minutos.`,
    careerAllComplete: "Carrera completada — ¡has conquistado la sala!",
    careerM1Title: "Primer Turno", careerM1Desc: "Atiende a dos clientes y aprende el ritmo del servicio.",
    careerM2Title: "Ronda de Bebidas", careerM2Desc: "Organiza pedidos por cursos en una mesa de tres.",
    careerM3Title: "Servicio de Almuerzo", careerM3Desc: "Cuatro clientes y un formato de pedido imprevisible.",
    careerM4Title: "Sin Segunda Oportunidad", careerM4Desc: "Cierra la mesa sin revisar el pedido al final.",
    careerM5Title: "Sala Llena", careerM5Desc: "Mantén el control de una mesa animada de seis.",
    careerM6Title: "Precisión Profesional", careerM6Desc: "Sin recapitulación y con una meta de precisión exigente.",
    careerM7Title: "Hora Punta", careerM7Desc: "Equilibra rapidez y precisión bajo presión de tiempo.",
    careerM8Title: "El Banquete", careerM8Desc: "Coordina ocho clientes en un servicio por rondas.",
    careerM9Title: "Prueba de Maître", careerM9Desc: "Diez clientes, 90% de precisión y ninguna ayuda.",
    badgeElephantTitle: "Memoria de Elefante",
    badgeElephantDesc: "Completa una mesa con 100% de acierto.",
    badgeSommelierTitle: "Sommelier en Entrenamiento",
    badgeSommelierDesc: "Alcanza 90% de precisión en Bebidas (mín. 10 pedidos).",
    badgeAgileTitle: "Servicio Ágil",
    badgeAgileDesc: "Cierra una mesa en menos de 3 minutos.",
    badgeCartmasterTitle: "Maestro de Carta",
    badgeCartmasterDesc: "Completa 10 mesas.",
    badgeGourmetTitle: "Experto Gourmet",
    badgeGourmetDesc: "Completa 25 mesas.",
    badgeBrigadeTitle: "Líder de Brigada",
    badgeBrigadeDesc: "Atiende una mesa con 8 o más personas.",
    badgeFirstServiceTitle: "Primer Servicio", badgeFirstServiceDesc: "Completa tu primera mesa.",
    badgePerfectFiveTitle: "Memoria Cinco Estrellas", badgePerfectFiveDesc: "Completa cinco mesas con 100% de precisión.",
    badgePolyglotTitle: "Sala Políglota", badgePolyglotDesc: "Completa mesas en portugués, inglés y español.",
    badgeRushMasterTitle: "Maestro de la Hora Punta", badgeRushMasterDesc: "Completa una Hora Punta dentro del límite.",
    badgeConfusionProofTitle: "A Prueba de Confusión", badgeConfusionProofDesc: "Consigue al menos 90% con pedidos similares.",
    badgeCareerGraduateTitle: "Graduado de la Academia", badgeCareerGraduateDesc: "Completa las nueve misiones de Carrera.",
  },
};
